import type { PlatformManifest } from './types.js';

const commonLiquidHandlingVocab = ['liquid-handling/v1'];
const assistPlanningToolIds = [
  'pipette_assist_voyager_4ch_300',
  'pipette_assist_voyager_4ch_1250',
  'pipette_assist_voyager_6ch_300',
  'pipette_assist_voyager_6ch_1250',
  'pipette_assist_voyager_8ch_12_5',
  'pipette_assist_voyager_8ch_50',
  'pipette_assist_voyager_8ch_125',
  'pipette_assist_voyager_8ch_300',
  'pipette_assist_voyager_8ch_1250',
  'pipette_assist_voyager_12ch_12_5',
  'pipette_assist_voyager_12ch_50',
  'pipette_assist_voyager_12ch_125',
  'pipette_assist_viaflow_8ch_12_5',
  'pipette_assist_viaflow_8ch_50',
  'pipette_assist_viaflow_8ch_125',
  'pipette_assist_viaflow_8ch_300',
  'pipette_assist_viaflow_8ch_1250',
  'pipette_assist_viaflow_12ch_12_5',
  'pipette_assist_viaflow_12ch_50',
  'pipette_assist_viaflow_12ch_125',
  'pipette_assist_viaflow_12ch_300',
  'pipette_assist_viaflow_12ch_1250',
  'pipette_assist_viaflow_16ch_12_5',
  'pipette_assist_viaflow_16ch_50',
  'pipette_assist_viaflow_16ch_125',
];

export const DEFAULT_PLATFORM_MANIFESTS: PlatformManifest[] = [
  {
    id: 'manual',
    label: 'Manual',
    allowedVocabIds: ['liquid-handling/v1', 'animal-handling/v1'],
    defaultVariant: 'manual_collapsed',
    toolTypeIds: [
      'pipette_1ch',
      'pipette_4ch_fixed',
      'pipette_6ch_fixed',
      'pipette_8ch_fixed',
      'pipette_12ch',
      'pipette_4ch_adjustable',
      'pipette_6ch_adjustable',
    ],
    compilerFamily: 'manual',
    modules: [],
    variants: [
      {
        id: 'manual_collapsed',
        title: 'Manual Technician Mode',
        slots: [],
      },
    ],
  },
  {
    id: 'integra_assist',
    label: 'Integra Assist Plus',
    allowedVocabIds: commonLiquidHandlingVocab,
    defaultVariant: 'assist_plus_3pos',
    toolTypeIds: assistPlanningToolIds,
    compilerFamily: 'assist_plus',
    modules: [
      { id: 'assist_heater', label: 'Assist Heater' },
      { id: 'mag_module', label: 'MAG / HEATMAG' },
      { id: 'coldplate', label: 'COLDPLATE / BIOSHAKE' },
    ],
    variants: [
      {
        id: 'assist_plus_3pos',
        title: 'Integra Assist Plus (3-position universal)',
        slots: [
          { id: 'A', kind: 'special', label: 'Pipette head park', orientationMode: 'flippable', row: 1, col: 1, reachable: false },
          { id: 'B', kind: 'standard', label: 'Portrait SBS slot', orientationMode: 'locked_portrait', row: 1, col: 2, reachable: true },
          { id: 'C', kind: 'standard', orientationMode: 'flippable', row: 1, col: 3, reachable: true },
          { id: 'D', kind: 'standard', orientationMode: 'flippable', row: 1, col: 4, reachable: true },
          { id: 'WASTE', kind: 'trash', label: 'Waste', orientationMode: 'not_applicable', row: 1, col: 5, reachable: false },
        ],
      },
      {
        id: 'assist_plus_4pos_portrait',
        title: 'Integra Assist Plus (4-position portrait)',
        slots: [
          { id: 'A', kind: 'special', label: 'Pipette head park', orientationMode: 'flippable', row: 1, col: 1, reachable: false },
          { id: 'B', kind: 'standard', label: 'Portrait SBS slot', orientationMode: 'locked_portrait', row: 1, col: 2, reachable: true },
          { id: 'C', kind: 'standard', orientationMode: 'flippable', row: 1, col: 3, reachable: true },
          { id: 'D', kind: 'standard', orientationMode: 'flippable', row: 1, col: 4, reachable: true },
          { id: 'E', kind: 'standard', orientationMode: 'flippable', row: 1, col: 5, reachable: true },
          { id: 'WASTE', kind: 'trash', label: 'Waste', orientationMode: 'not_applicable', row: 1, col: 6, reachable: false },
        ],
      },
    ],
  },
  {
    id: 'opentrons_ot2',
    label: 'Opentrons OT-2',
    allowedVocabIds: commonLiquidHandlingVocab,
    defaultVariant: 'ot2_standard',
    toolTypeIds: ['pipette_1ch', 'pipette_8ch_fixed', 'pipette_12ch'],
    compilerFamily: 'opentrons',
    modules: [
      { id: 'heater_shaker', label: 'Heater-Shaker' },
      { id: 'temperature', label: 'Temperature Module' },
      { id: 'magnetic', label: 'Magnetic Module' },
    ],
    variants: [
      {
        id: 'ot2_standard',
        title: 'Opentrons OT-2',
        slots: [
          { id: '1', kind: 'standard', row: 4, col: 1, reachable: true },
          { id: '2', kind: 'standard', row: 4, col: 2, reachable: true },
          { id: '3', kind: 'standard', row: 4, col: 3, reachable: true },
          { id: '4', kind: 'standard', row: 3, col: 1, reachable: true },
          { id: '5', kind: 'standard', row: 3, col: 2, reachable: true },
          { id: '6', kind: 'standard', row: 3, col: 3, reachable: true },
          { id: '7', kind: 'standard', row: 2, col: 1, reachable: true },
          { id: '8', kind: 'standard', row: 2, col: 2, reachable: true },
          { id: '9', kind: 'standard', row: 2, col: 3, reachable: true },
          { id: '10', kind: 'standard', row: 1, col: 1, reachable: true },
          { id: '11', kind: 'standard', row: 1, col: 2, reachable: true },
          { id: '12', kind: 'trash', label: 'Fixed trash', orientationMode: 'not_applicable', row: 1, col: 3, reachable: false },
        ],
      },
    ],
  },
  {
    id: 'opentrons_flex',
    label: 'Opentrons Flex',
    allowedVocabIds: commonLiquidHandlingVocab,
    defaultVariant: 'ot3_standard',
    toolTypeIds: ['pipette_1ch', 'pipette_8ch_fixed', 'pipette_96ch'],
    compilerFamily: 'opentrons',
    modules: [
      { id: 'heater_shaker', label: 'Heater-Shaker' },
      { id: 'temperature', label: 'Temperature Module' },
      { id: 'magnetic', label: 'Magnetic Module' },
      { id: 'waste_chute', label: 'Waste Chute' },
      { id: 'gripper_staging', label: 'Staging Column' },
    ],
    variants: [
      {
        id: 'ot3_standard',
        title: 'Opentrons Flex',
        slots: [
          { id: 'A1', kind: 'standard', row: 1, col: 1, reachable: true },
          { id: 'A2', kind: 'standard', row: 1, col: 2, reachable: true },
          { id: 'A3', kind: 'trash', label: 'Trash bin', orientationMode: 'not_applicable', row: 1, col: 3, reachable: false },
          { id: 'A4', kind: 'special', label: 'Staging', orientationMode: 'not_applicable', row: 1, col: 4, reachable: false, stagingOnly: true },
          { id: 'B1', kind: 'standard', row: 2, col: 1, reachable: true },
          { id: 'B2', kind: 'standard', row: 2, col: 2, reachable: true },
          { id: 'B3', kind: 'standard', row: 2, col: 3, reachable: true },
          { id: 'B4', kind: 'special', label: 'Staging', orientationMode: 'not_applicable', row: 2, col: 4, reachable: false, stagingOnly: true },
          { id: 'C1', kind: 'standard', row: 3, col: 1, reachable: true },
          { id: 'C2', kind: 'standard', row: 3, col: 2, reachable: true },
          { id: 'C3', kind: 'standard', row: 3, col: 3, reachable: true },
          { id: 'C4', kind: 'special', label: 'Staging', orientationMode: 'not_applicable', row: 3, col: 4, reachable: false, stagingOnly: true },
          { id: 'D1', kind: 'standard', row: 4, col: 1, reachable: true },
          { id: 'D2', kind: 'standard', row: 4, col: 2, reachable: true },
          { id: 'D3', kind: 'special', label: 'Chute/Accessory', orientationMode: 'not_applicable', row: 4, col: 3, reachable: false },
          { id: 'D4', kind: 'special', label: 'Staging', orientationMode: 'not_applicable', row: 4, col: 4, reachable: false, stagingOnly: true },
        ],
      },
    ],
  },
];
