import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { parse, stringify } from 'yaml'
import { AppShell } from '../shared/shell'
import { useAiChat } from '../shared/hooks/useAiChat'
import { useRegisterAiChat } from '../shared/context/AiPanelContext'
import { sequenceApi, requestId, recordRef } from './api'
import { SequenceImport } from './SequenceImport'
import { SequenceChat } from './SequenceChat'
import { SequenceEditor, type SequenceEditorHandle } from './SequenceEditor'
import { SequenceResults } from './SequenceResults'
import './SequencesPage.css'
interface RecordItem {recordId:string;payload:Record<string,any>;meta?:{contentSha?:string;commitSha?:string}}
const tabs=['Editor','Assay','Analysis','Setup','Import','Knowledge'] as const
export function SequencesPage() {
 const [search]=useSearchParams();const [tab,setTab]=useState<typeof tabs[number]>(search.has('source')?'Import':'Editor')
 const [records,setRecords]=useState<RecordItem[]>([]);const [contract,setContract]=useState<any>(null);const [selected,setSelected]=useState('');const [query,setQuery]=useState('')
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [proposal,setProposal]=useState(()=>{try{return stringify(JSON.parse(sessionStorage.getItem('cl-sequence-proposal')??'null'))?.replace(/^null\n$/,'')??''}catch{return ''}});const [prompt,setPrompt]=useState('');const [result,setResult]=useState<any>(null)
 const [reporter,setReporter]=useState('');const [quencher,setQuencher]=useState('');const [oligoSequence,setOligoSequence]=useState('')
 const [readoutName,setReadoutName]=useState('FAM');const [instrumentType,setInstrumentType]=useState('qpcr');const [readoutMode,setReadoutMode]=useState('ct')
 const [assayName,setAssayName]=useState('');const [forward,setForward]=useState('');const [reverse,setReverse]=useState('');const [probe,setProbe]=useState('');const [channel,setChannel]=useState('');const [expectedLength,setExpectedLength]=useState('');const [target,setTarget]=useState('')
 const [operation,setOperation]=useState('run_virtual_pcr');const [endpointId,setEndpointId]=useState('');const [inputs,setInputs]=useState<Record<string,string>>({});const [parameters,setParameters]=useState<Record<string,any>>({minLength:50,maxLength:1000,maxMismatches:0,exactThreePrime:8,maxProducts:1000})
 const [endpoint,setEndpoint]=useState<any>({kind:'sequence-endpoint',id:'',label:'',engine:'virtual-pcr',runtime:'builtin',version:'1.0.0',timeoutSeconds:120,threads:1})
 const [interpretation,setInterpretation]=useState<Record<string,string>>({});const [controlInputs,setControlInputs]=useState<Record<string,string>>({});const [statement,setStatement]=useState('')
 const [collectionName,setCollectionName]=useState('');const [members,setMembers]=useState<string[]>([]);const [start,setStart]=useState(1);const [end,setEnd]=useState(1);const [regionName,setRegionName]=useState('')
 const refresh=useCallback(async()=>{const data=await sequenceApi('/catalog');setRecords(data.records)},[])
 useEffect(()=>{Promise.all([refresh(),sequenceApi('/contract').then(setContract)]).catch(e=>setError(e.message))},[refresh])
 const byKind=(kind:string)=>records.filter(r=>r.payload.kind===kind)
 const choices=records.filter(r=>['sequence','oligo-spec','sequence-collection'].includes(r.payload.kind))
 const selectOptions=(list:RecordItem[])=>list.map(r=><option key={r.recordId} value={r.recordId}>{r.payload.label??r.payload.name??r.payload.title??r.recordId}</option>)
 const editorRef=useRef<SequenceEditorHandle>(null)
 const [editorContext,setEditorContext]=useState<Record<string,any>>({})
 const onSequenceProposal=useCallback((p:Record<string,unknown>,userRequest?:string)=>{
  if(['save_sequence','create_oligo'].includes(String(p.operation))){
   setTab('Editor');setProposal('');editorRef.current?.propose(p,userRequest);sessionStorage.removeItem('cl-sequence-proposal')
  }else{setProposal(stringify(p));setMessage('Review the proposed action before applying it.')}
 },[])
 useEffect(()=>{try{const pending=JSON.parse(sessionStorage.getItem('cl-sequence-proposal')??'null');if(pending)onSequenceProposal(pending)}catch{/* Keep malformed handoffs inspectable. */}},[onSequenceProposal])
 const aiContext=useMemo(()=>({surface:'sequences' as const,summary:`Sequence workspace — ${tab}`,surfaceContext:{...editorContext,selectedRecordId:selected,records:records.map(r=>({id:r.recordId,kind:r.payload.kind,label:r.payload.label??r.payload.name??r.payload.title,alphabet:r.payload.alphabet,length:r.payload.length,...(r.recordId===selected&&r.payload.residues?.length<=20000?{residues:r.payload.residues}:{}),...(r.payload.kind==='sequence-endpoint'?{configuration:r.payload}:{}),...(r.payload.oligos?{oligos:r.payload.oligos}:{}),...(r.payload.channel_label?{channel:r.payload.channel_label}:{}),...(r.payload.outputArtifactRefs?{outputArtifactRefs:r.payload.outputArtifactRefs}:{}),...(r.payload.statement?{statement:r.payload.statement}:{}),...(r.payload.kind==='measurement-context'?{measurementContext:r.payload}:{}),...(r.payload.kind==='sequence-interpretation-rule'?{rule:r.payload}:{})})),availableOperations:contract?.capabilities?.engines,selection:inputs,parameters,lastActionResult:result}}),[tab,selected,records,contract,inputs,parameters,result,editorContext])
 const chat=useAiChat({aiContext,onSequenceProposal,endpoint:'sequences',proposalScopeKey:`${selected}:${editorContext.proposalScopeKey}`});useRegisterAiChat(chat)
 const act=async(action:any)=>{
  setBusy(true);setError('');setMessage('')
  try{const data=await sequenceApi('/actions',{requestId:requestId(),...action});setResult(data);setMessage(data.recordId?`Saved ${data.recordId}${data.status?` — ${data.status}`:''}`:'Action completed.');await refresh();return data}
  catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}
 }
 const fire=(action:any)=>{void act(action).catch(()=>{})}
 function selectRecord(id:string) {if(editorRef.current?.canLeave()===false)return;setSelected(id);setTab('Editor');setOligoSequence(id)}
 async function open(record:RecordItem) {selectRecord(record.recordId)}
 function changeOperation(value:string) {
  setOperation(value);setEndpointId('');setInputs({});setParameters(value==='run_virtual_pcr'?{minLength:50,maxLength:1000,maxMismatches:0,exactThreePrime:8,maxProducts:1000}:value==='run_mafft'?{strategy:'auto',maxIterations:0}:{task:'blastn',evalue:0.001,maxHits:100})
 }
 const actionSpec=contract?.schema?.oneOf?.find((x:any)=>x.properties.operation.const===operation)
 const editor=<>
  <SequenceEditor ref={editorRef} recordId={selected} contract={contract} onSelect={selectRecord} onAccepted={refresh} onContext={setEditorContext}/>
  <fieldset><legend>Import FASTA</legend><input aria-label="FASTA file" type="file" accept=".fa,.fasta,.fna,.faa,.txt" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const contents=await file.text();if(!contents.trimStart().startsWith('>'))throw new Error('FASTA must start with a >name header.');const entries=contents.trimStart().split(/^>/m).filter(x=>x.trim());if(entries.some(entry=>!entry.split(/\r?\n/)[0].trim()||!entry.split(/\r?\n/).slice(1).join('').trim()))throw new Error('Every FASTA entry needs a name and sequence.');const refs=[];for(const entry of entries){const [name,...lines]=entry.split(/\r?\n/);const saved=await act({operation:'save_sequence',sequence:{label:name.trim(),residues:lines.join(''),alphabet:editorContext.workingForm?.sequence.alphabet??'iupac_dna',topology:editorContext.workingForm?.sequence.topology??'linear'}});refs.push(recordRef(saved.recordId))}if(refs.length)await act({operation:'save_collection',label:file.name,members:refs})}catch(e){setError((e as Error).message)}}}/></fieldset>
  <fieldset><legend>Annotate a region</legend><label>Region name<input value={regionName} onChange={e=>setRegionName(e.target.value)}/></label><div className="sequence-fields"><label>Start (1-based)<input type="number" min="1" value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>End (inclusive)<input type="number" min={start} value={end} onChange={e=>setEnd(Number(e.target.value))}/></label></div><button disabled={busy||!selected||!regionName} onClick={()=>fire({operation:'save_interval',label:regionName,sequenceRef:recordRef(selected),start,end,strand:editorContext.workingForm?.sequence.alphabet==='protein'?'na':'+'})}>Save region</button></fieldset>
 </>
 const assay=<>
  <fieldset><legend>Oligo specification</legend><label>Sequence<select value={oligoSequence} onChange={e=>setOligoSequence(e.target.value)}><option value="">Select sequence…</option>{selectOptions(byKind('sequence'))}</select></label><label>5′ reporter<input placeholder="e.g. FAM" value={reporter} onChange={e=>setReporter(e.target.value)}/></label><label>3′ quencher<input placeholder="e.g. BHQ-1" value={quencher} onChange={e=>setQuencher(e.target.value)}/></label><button disabled={busy||!oligoSequence} onClick={async()=>{try{const snapshot=await act({operation:'pin_sequence',sequenceRef:recordRef(oligoSequence)});const pinned=snapshot.revisionRef;await act({operation:'save_oligo',oligo:{kind:'oligo-spec',id:`OLIGO-${requestId()}`,label:records.find(r=>r.recordId===oligoSequence)?.payload.label,sequenceRef:pinned,modifications:[...(reporter?[{position:'5-prime',role:'reporter',label:reporter}]:[]),...(quencher?[{position:'3-prime',role:'quencher',label:quencher}]:[])]}})}catch{}}}>Save oligo</button></fieldset>
  <fieldset><legend>Create a readout</legend><label>Channel / readout name<input value={readoutName} onChange={e=>setReadoutName(e.target.value)}/></label><label>Instrument type<select value={instrumentType} onChange={e=>setInstrumentType(e.target.value)}><option value="qpcr">qPCR</option><option value="other">Gel / other</option></select></label><label>Readout mode<select value={readoutMode} onChange={e=>setReadoutMode(e.target.value)}><option value="ct">Ct</option><option value="fluorescence">Fluorescence</option><option value="image_feature">Image feature / band</option></select></label><button disabled={busy||!readoutName} onClick={async()=>{try{const saved=await act({operation:'save_readout',readout:{kind:'readout-definition',id:`RDEF-${requestId()}`,name:readoutName,channel_label:readoutName,instrument_type:instrumentType,mode:readoutMode}});setChannel(saved.recordId)}catch{}}}>Save readout</button></fieldset>
  <fieldset><legend>Assay roles and readout</legend><label>Assay name<input value={assayName} onChange={e=>setAssayName(e.target.value)}/></label>
   {([['Forward primer',forward,setForward],['Reverse primer',reverse,setReverse],['Probe',probe,setProbe]] as const).map(([name,value,set])=><label key={name}>{name}<select value={value} onChange={e=>set(e.target.value)}><option value="">Select oligo…</option>{selectOptions(byKind('oligo-spec'))}</select></label>)}
   <label>Probe reports in<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Select readout…</option>{selectOptions(byKind('readout-definition'))}</select></label>
   <label>Target ontology ID<input value={target} placeholder="NCBITaxon:…" onChange={e=>setTarget(e.target.value)}/></label><label>Expected product length (bp)<input type="number" min="1" value={expectedLength} onChange={e=>setExpectedLength(e.target.value)}/></label>
   <button disabled={busy||!assayName||!forward||!reverse||!channel} onClick={()=>fire({operation:'save_assay',assay:{kind:'assay-definition',id:`ASSAY-${requestId()}`,name:assayName,assay_type:'PCR',instrument_type:records.find(r=>r.recordId===channel)?.payload.instrument_type??'qpcr',readout_def_refs:[recordRef(channel,'readout-definition')],...(target?{target_refs:[{kind:'ontology',id:target,namespace:target.split(':')[0],label:target}]}:{}),...(expectedLength?{expectedProductLength:Number(expectedLength)}:{}),oligos:[{role:'forward_primer',oligoRef:recordRef(forward,'oligo-spec')},{role:'reverse_primer',oligoRef:recordRef(reverse,'oligo-spec')},...(probe?[{role:'probe',oligoRef:recordRef(probe,'oligo-spec'),readoutRef:recordRef(channel,'readout-definition')}]:[])]}})}>Save assay</button>
  </fieldset>
  {byKind('assay-definition').filter(r=>r.payload.oligos).map(r=><details key={r.recordId}><summary>{r.payload.name}</summary><pre>{stringify(r.payload)}</pre></details>)}
 </>
 const analysis=<>
  <label>Analysis<select value={operation} onChange={e=>changeOperation(e.target.value)}>{contract?.capabilities?.engines.map((e:any)=><option key={e.id} value={e.operation}>{e.label}</option>)}</select></label>
  <label>Configured endpoint<select value={endpointId} onChange={e=>setEndpointId(e.target.value)}><option value="">Select endpoint…</option>{selectOptions(byKind('sequence-endpoint').filter(r=>r.payload.engine===operation.slice(4).replace('_','-')))}</select></label>
  {Object.keys(actionSpec?.properties.inputs.properties??{}).map(name=><label key={name}>{name}{actionSpec.properties.inputs.required.includes(name)?' *':' (optional)'}<select value={inputs[name]??''} onChange={e=>setInputs({...inputs,[name]:e.target.value})}><option value="">Select sequence, oligo or collection…</option>{selectOptions(choices)}</select></label>)}
  {Object.entries(actionSpec?.properties.parameters.properties??{}).map(([name,spec]:[string,any])=><label key={name}>{name}{spec.enum?<select value={parameters[name]??''} onChange={e=>setParameters({...parameters,[name]:e.target.value})}>{spec.enum.map((v:string)=><option key={v}>{v}</option>)}</select>:<input type="number" min={spec.minimum??0} step={spec.type==='integer'?1:'any'} value={parameters[name]??''} onChange={e=>setParameters({...parameters,[name]:Number(e.target.value)})}/>}</label>)}
  <button disabled={busy||!endpointId} onClick={()=>fire({operation,endpointRef:recordRef(endpointId,'sequence-endpoint'),label:`${operation.slice(4)} analysis`,inputs:Object.fromEntries(Object.entries(inputs).filter(([,v])=>v).map(([k,v])=>[k,recordRef(v)])),parameters})}>Run analysis</button>
  <SequenceResults manifest={result?.manifest}/>
  <fieldset><legend>Saved analysis runs</legend>{byKind('analysis-run').filter(r=>r.payload.frozenRevisionRef).map(r=><p key={r.recordId}><button onClick={()=>setResult({recordId:r.recordId,manifest:r.payload.outputManifest})}>{r.payload.title} — {r.payload.status}</button></p>)}</fieldset>
  <fieldset><legend>Reference / alignment collection</legend><label>Collection name<input value={collectionName} onChange={e=>setCollectionName(e.target.value)}/></label>{byKind('sequence').map(r=><label key={r.recordId}><input type="checkbox" checked={members.includes(r.recordId)} onChange={e=>setMembers(e.target.checked?[...members,r.recordId]:members.filter(id=>id!==r.recordId))}/>{r.payload.label}</label>)}<button disabled={busy||!collectionName||!members.length} onClick={()=>fire({operation:'save_collection',label:collectionName,members:members.map(id=>recordRef(id))})}>Save collection</button></fieldset>
 </>
 const setup=<>
  <button disabled={busy} onClick={()=>fire({operation:'discover_endpoints'})}>Discover installed engines</button>
  {result?.endpoints&&<pre>{stringify(result.endpoints)}</pre>}
  <p>Configure an installed local tool or a container image pinned by digest. Virtual PCR runs locally without additional software.</p>
  <label>Engine<select value={endpoint.engine} onChange={e=>setEndpoint({kind:'sequence-endpoint',id:'',label:'',engine:e.target.value,runtime:e.target.value==='virtual-pcr'?'builtin':'local',version:e.target.value==='virtual-pcr'?'1.0.0':'',threads:1,timeoutSeconds:120})}>{contract?.capabilities?.engines.map((e:any)=><option key={e.id}>{e.id}</option>)}</select></label>
  <label>Name<input value={endpoint.label} onChange={e=>setEndpoint({...endpoint,label:e.target.value})}/></label>
  {endpoint.engine!=='virtual-pcr'&&<><label>Runtime<select value={endpoint.runtime} onChange={e=>setEndpoint({...endpoint,runtime:e.target.value})}><option value="local">Installed executable</option><option value="container">Docker container</option></select></label><label>Expected software version<input value={endpoint.version} onChange={e=>setEndpoint({...endpoint,version:e.target.value})}/></label>{endpoint.runtime==='local'?<>{['executable',...(endpoint.engine==='blastn'?['databaseBuilder']:[])].map(field=><label key={field}>{field==='executable'?'Executable path':'makeblastdb path'}<input value={endpoint[field]??''} onChange={e=>setEndpoint({...endpoint,[field]:e.target.value,[`${field}Sha256`]:''})}/><button disabled={!endpoint[field]||busy} onClick={async()=>{try{const r=await sequenceApi('/executable',{path:endpoint[field]});setEndpoint({...endpoint,[`${field}Sha256`]:r.sha256})}catch(e){setError((e as Error).message)}}}>Read checksum</button><small>{endpoint[`${field}Sha256`]}</small></label>)}</>:<label>Container image with @sha256 digest<input value={endpoint.image??''} onChange={e=>setEndpoint({...endpoint,image:e.target.value})}/></label>}</>}
  <button disabled={busy||!endpoint.label||!endpoint.version} onClick={()=>fire({operation:'configure_endpoint',endpoint:{...endpoint,id:`SEQEP-${requestId()}`}})}>Verify and save endpoint</button>
  {endpoint.runtime==='container'&&<button disabled={busy||!endpoint.image||!endpoint.version||!endpoint.label} onClick={()=>fire({operation:'deploy_endpoint',endpoint:{...endpoint,id:`SEQEP-${requestId()}`}})}>Download pinned image, verify and save</button>}
  {byKind('sequence-endpoint').map(r=><details key={r.recordId}><summary>{r.payload.label} · {r.payload.engine} {r.payload.version}</summary><pre>{stringify(r.payload)}</pre></details>)}
 </>
 const activeRule=records.find(r=>r.recordId===interpretation.ruleRef)?.payload
 const knowledge=<><p>Interpretation links a claim, biological context, assay, measurement context, result and controls. Computational predictions remain distinct from observed evidence.</p><p>Use the chat to propose a rule or edit a structured request below. Required controls and both detection criteria are explicit.</p>
  <fieldset><legend>Evaluate evidence in context</legend>
   {([['ruleRef','Interpretation rule','sequence-interpretation-rule'],['claimRef','Claim','claim'],['contextRef','Biological context','context'],['measurementContextRef','Measurement context','measurement-context'],['resultRef','Result artifact','analysis-output-artifact']] as const).map(([field,title,kind])=><label key={field}>{title}<select value={interpretation[field]??''} onChange={e=>setInterpretation({...interpretation,[field]:e.target.value})}><option value="">Select…</option>{selectOptions(byKind(kind))}</select></label>)}
   {(activeRule?.requiredControls??[]).map((name:string)=><label key={name}>Control: {name}<select value={controlInputs[name]??''} onChange={e=>setControlInputs({...controlInputs,[name]:e.target.value})}><option value="">Select result artifact…</option>{selectOptions(byKind('analysis-output-artifact'))}</select></label>)}
   <label>Contextual statement<textarea value={statement} onChange={e=>setStatement(e.target.value)}/></label>
   <button disabled={busy||!statement||!interpretation.ruleRef||!interpretation.claimRef||!interpretation.contextRef||!interpretation.resultRef} onClick={()=>fire({operation:'interpret',statement,...Object.fromEntries(Object.entries(interpretation).filter(([,v])=>v).map(([k,v])=>[k,recordRef(v,records.find(r=>r.recordId===v)?.payload.kind)])),controls:Object.fromEntries(Object.entries(controlInputs).filter(([,v])=>v).map(([k,v])=>[k,recordRef(v,'analysis-output-artifact')]))})}>Evaluate and save assertion</button>
   {result?.detection&&<p role="status">{result.detection} · Assertion {result.assertionId} · Evidence {result.evidenceId}</p>}
  </fieldset>
  {byKind('assertion').filter(r=>r.payload.outcome?.detection).map(r=><details key={r.recordId}><summary>{r.payload.statement} — {r.payload.outcome.detection}</summary><pre>{stringify(r.payload)}</pre>{byKind('evidence').filter(e=>[...(e.payload.supports??[]),...(e.payload.refutes??[]),...(e.payload.assesses??[])].some((s:any)=>s.id===r.recordId)).map(e=><pre key={e.recordId}>{stringify(e.payload)}</pre>)}</details>)}
 {byKind('sequence-interpretation-rule').map(r=><details key={r.recordId}><summary>{r.payload.label??r.recordId}</summary><pre>{stringify(r.payload)}</pre></details>)}</>
 return <AppShell brand="Sequences" layout="workspace" leftPane={<main className="sequences-page">
  <h1>Sequences &amp; assays</h1><nav aria-label="Sequence workspace">{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {editorContext.draft&&tab!=='Editor'&&<button onClick={()=>setTab('Editor')}>Review sequence proposal</button>}
  <div hidden={tab!=='Editor'}>{editor}</div>
  {tab==='Editor'?null:tab==='Assay'?assay:tab==='Analysis'?analysis:tab==='Setup'?setup:tab==='Import'?<SequenceImport onSaved={()=>void refresh()} initialSource={search.get('source')??undefined} initialAccession={search.get('accession')??undefined}/>:knowledge}
  {busy&&<p role="status">Working…</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}
  <details open={!!proposal}><summary>Structured action request</summary><textarea aria-label="Action YAML" rows={12} value={proposal} onChange={e=>setProposal(e.target.value)}/><button disabled={!proposal||busy} onClick={async()=>{try{const action=parse(proposal);if(['save_sequence','create_oligo'].includes(action.operation)){onSequenceProposal(action);return}const data=await act(action);setProposal('');sessionStorage.removeItem('cl-sequence-proposal');if(data.manifest)setTab('Analysis')}catch(e){setError((e as Error).message)}}}>Accept and apply</button><button disabled={busy} onClick={()=>{setProposal('');sessionStorage.removeItem('cl-sequence-proposal')}}>Discard</button></details>
 </main>} navPane={<aside className="sequences-page sequence-library"><h2>Library</h2><input aria-label="Search sequences" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find sequence…"/>{records.filter(r=>['sequence','oligo-spec'].includes(r.payload.kind)).filter(r=>`${r.payload.label} ${r.recordId}`.toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.recordId} onClick={()=>void open(r)}>{r.payload.label}<small>{r.payload.kind==='oligo-spec'?'Oligo':`${r.payload.length??r.payload.residues?.length} residues`}</small></button>)}</aside>} rightPane={<SequenceChat messages={chat.messages} isStreaming={chat.isStreaming} prompt={prompt} onPromptChange={setPrompt} onReview={onSequenceProposal} onSend={()=>{chat.sendPrompt(prompt);setPrompt('')}} onCancel={chat.cancelStream}/>}/>

}
