/**
 * ProtocolIdeGraphReviewSurface — review-only event-graph surface for Protocol IDE sessions.
 *
 * This surface reuses the existing graph/editor stack in a read-only mode.
 * It renders:
 *   - latest compiler output on the event graph canvas,
 *   - deck/labware summaries,
 *   - tools/instruments summaries,
 *   - reagents/concentrations summaries,
 *   - budget/cost summaries,
 *   - issue cards as canvas overlays / badges linked to graph regions and source evidence.
 *
 * v1 is review-only: no direct graph editing, no mutation of graph structure.
 */

import { type ReactNode } from 'react'
import type { ProtocolIdeSession } from './types'
import type { DeckPlacement } from '../graph/labware/DeckVisualizationPanel'
import type { Labware } from '../types/labware'
import type { PlateEvent } from '../types/events'
import { CommentBadge } from './CommentBadge'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Anchor for a feedback comment. */
export type CommentAnchor =
  | { kind: 'node'; semanticKey: string; instanceId?: string }
  | { kind: 'phase'; phaseId: string }
  | { kind: 'source'; documentRef: string; page: number }

/** A feedback comment with anchors. */
export interface FeedbackComment {
  id: string
  text: string
  anchors: CommentAnchor[]
  createdAt: string
}

/** Minimal issue card reference (matches spec-073 issue-card-generator). */
export interface IssueCardRef {
  id: string
  title: string
  severity: 'error' | 'warning' | 'info'
  /** Graph region identifier this card is linked to (e.g. event ID, labware ID). */
  graphRegionId?: string
  /** Evidence citation ID linking back to source PDF. */
  evidenceRefId?: string
  /** Short description. */
  description?: string
}

/** Deck/labware summary data. */
export interface DeckLabwareSummary {
  labwares: Array<{
    labwareId: string
    name: string
    labwareType: string
    slotId?: string
    orientation?: 'portrait' | 'landscape'
  }>
  placements: DeckPlacement[]
}

/** Tools/instruments summary data. */
export interface ToolsInstrumentsSummary {
  tools: Array<{
    toolTypeId: string
    label: string
    channelCount?: number
  }>
}

/** Reagents/concentrations summary data. */
export interface ReagentsConcentrationsSummary {
  reagents: Array<{
    compoundId: string
    label: string
    volume?: number
    concentration?: number
    unit?: string
  }>
}

/** Budget/cost summary data. */
export interface BudgetCostSummary {
  lineCount: number
  approvedLineCount: number
  grandTotal: number
}

/** Event-graph data from the latest compiler output. */
export interface EventGraphData {
  events: PlateEvent[]
  labwares: Labware[]
  deckPlacements: DeckPlacement[]
}

/** Props for the review surface. */
export interface ProtocolIdeGraphReviewSurfaceProps {
  /** The current Protocol IDE session. */
  session: ProtocolIdeSession
  /** Latest compiler output (event graph data). */
  eventGraphData?: EventGraphData | null
  /** Deck/labware summary. */
  deckLabwareSummary?: DeckLabwareSummary | null
  /** Tools/instruments summary. */
  toolsInstrumentsSummary?: ToolsInstrumentsSummary | null
  /** Reagents/concentrations summary. */
  reagentsConcentrationsSummary?: ReagentsConcentrationsSummary | null
  /** Budget/cost summary. */
  budgetCostSummary?: BudgetCostSummary | null
  /** Issue cards generated by the issue-card-generator. */
  issueCards?: IssueCardRef[]
  /** Feedback comments with anchors. */
  comments?: FeedbackComment[]
  /** Callback when a user clicks on an issue card badge. */
  onIssueCardClick?: (card: IssueCardRef) => void
  /** Callback when a user clicks on an evidence citation. */
  onEvidenceClick?: (evidenceRefId: string) => void
  /** When set, highlights the matching graph node. */
  highlightedEvidenceRefId?: string | null
}

// ---------------------------------------------------------------------------
// Issue card badge component
// ---------------------------------------------------------------------------

function IssueCardBadge({
  card,
  onClick,
}: {
  card: IssueCardRef
  onClick?: (card: IssueCardRef) => void
}): JSX.Element {
  const severityColor =
    card.severity === 'error'
      ? '#dc2626'
      : card.severity === 'warning'
        ? '#f59e0b'
        : '#2563eb'

  return (
    <button
      className="protocol-ide-issue-badge"
      data-testid={`issue-badge-${card.id}`}
      style={{
        background: severityColor,
        color: '#fff',
        border: 'none',
        borderRadius: '999px',
        padding: '0.15rem 0.5rem',
        fontSize: '0.7rem',
        fontWeight: 700,
        cursor: 'pointer',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        whiteSpace: 'nowrap',
      }}
      title={card.description ?? card.title}
      onClick={() => onClick?.(card)}
    >
      <span className="protocol-ide-issue-badge__dot" style={{ background: '#fff', borderRadius: '50%', width: '6px', height: '6px', display: 'inline-block' }} />
      {card.title}
    </button>
  )
}

// ---------------------------------------------------------------------------
// Issue card overlay (canvas overlay for issue cards)
// ---------------------------------------------------------------------------

function IssueCardOverlay({
  card,
  onEvidenceClick,
}: {
  card: IssueCardRef
  onEvidenceClick?: (evidenceRefId: string) => void
}): JSX.Element {
  return (
    <div
      className="protocol-ide-issue-overlay"
      data-testid={`issue-overlay-${card.id}`}
    >
      <div className="protocol-ide-issue-overlay__header">
        <span
          className="protocol-ide-issue-overlay__severity"
          style={{
            background:
              card.severity === 'error'
                ? '#dc2626'
                : card.severity === 'warning'
                  ? '#f59e0b'
                  : '#2563eb',
          }}
        >
          {card.severity}
        </span>
        <strong>{card.title}</strong>
      </div>
      {card.description && (
        <p className="protocol-ide-issue-overlay__description">{card.description}</p>
      )}
      {card.evidenceRefId && onEvidenceClick && (
        <button
          className="protocol-ide-issue-overlay__evidence-link"
          data-testid={`evidence-link-${card.evidenceRefId}`}
          onClick={() => onEvidenceClick(card.evidenceRefId!)}
        >
          View source evidence
        </button>
      )}
      <style>{`
        .protocol-ide-issue-overlay {
          position: absolute;
          top: 0.75rem;
          right: 0.75rem;
          max-width: 240px;
          padding: 0.6rem 0.75rem;
          border-radius: 10px;
          background: rgba(255, 255, 255, 0.92);
          border: 1px solid rgba(208, 215, 222, 0.9);
          box-shadow: 0 4px 16px rgba(31, 35, 40, 0.1);
          backdrop-filter: blur(8px);
          z-index: 10;
          font-size: 0.8rem;
        }
        .protocol-ide-issue-overlay__header {
          display: flex;
          align-items: center;
          gap: 0.4rem;
          margin-bottom: 0.3rem;
        }
        .protocol-ide-issue-overlay__severity {
          font-size: 0.6rem;
          font-weight: 700;
          color: #fff;
          padding: 0.1rem 0.35rem;
          border-radius: 999px;
          text-transform: uppercase;
        }
        .protocol-ide-issue-overlay__description {
          margin: 0.3rem 0;
          color: #495057;
          line-height: 1.4;
        }
        .protocol-ide-issue-overlay__evidence-link {
          font-size: 0.72rem;
          color: #2563eb;
          background: none;
          border: none;
          text-decoration: underline;
          cursor: pointer;
          padding: 0;
        }
        .protocol-ide-issue-overlay__evidence-link:hover {
          color: #1d4ed8;
        }
      `}</style>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Summary panel component (reusable for all four summary families)
// ---------------------------------------------------------------------------

function SummaryPanel({
  title,
  icon,
  children,
  dataTestId,
}: {
  title: string
  icon: string
  children: ReactNode
  dataTestId?: string
}): JSX.Element {
  return (
    <section
      className="protocol-ide-summary-panel"
      data-testid={dataTestId}
    >
      <div className="protocol-ide-summary-panel__header">
        <span className="protocol-ide-summary-panel__icon">{icon}</span>
        <h3 className="protocol-ide-summary-panel__title">{title}</h3>
      </div>
      <div className="protocol-ide-summary-panel__body">{children}</div>
      <style>{`
        .protocol-ide-summary-panel {
          border: 1px solid #d0d7de;
          border-radius: 8px;
          background: #fff;
          overflow: hidden;
        }
        .protocol-ide-summary-panel__header {
          display: flex;
          align-items: center;
          gap: 0.4rem;
          padding: 0.5rem 0.75rem;
          background: #f8f9fa;
          border-bottom: 1px solid #e9ecef;
        }
        .protocol-ide-summary-panel__icon {
          font-size: 1rem;
        }
        .protocol-ide-summary-panel__title {
          margin: 0;
          font-size: 0.82rem;
          font-weight: 600;
          color: #212529;
        }
        .protocol-ide-summary-panel__body {
          padding: 0.6rem 0.75rem;
          font-size: 0.8rem;
          color: #495057;
        }
      `}</style>
    </section>
  )
}

// ---------------------------------------------------------------------------
// Deck & Labware summary
// ---------------------------------------------------------------------------

function DeckLabwareSummaryView({
  summary,
}: {
  summary: DeckLabwareSummary
}): JSX.Element {
  return (
    <SummaryPanel title="Deck & Labware" icon="🧪" dataTestId="summary-deck-labware">
      {summary.placements.length > 0 ? (
        <div className="protocol-ide-summary-deck-grid">
          {summary.placements.map((p) => (
            <div key={p.slotId} className="protocol-ide-summary-deck-slot" data-testid={`deck-slot-${p.slotId}`}>
              <span className="protocol-ide-summary-deck-slot__id">{p.slotId}</span>
              {p.labwareId && (
                <span className="protocol-ide-summary-deck-slot__name">
                  {summary.labwares.find((l) => l.labwareId === p.labwareId)?.name ?? p.labwareId}
                </span>
              )}
            </div>
          ))}
        </div>
      ) : (
        <p className="protocol-ide-summary-empty">No labware placed yet.</p>
      )}
      <style>{`
        .protocol-ide-summary-deck-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
          gap: 0.35rem;
        }
        .protocol-ide-summary-deck-slot {
          display: flex;
          align-items: center;
          gap: 0.35rem;
          padding: 0.3rem 0.5rem;
          background: #f1f5f9;
          border-radius: 6px;
          font-size: 0.75rem;
        }
        .protocol-ide-summary-deck-slot__id {
          font-weight: 700;
          color: #1e293b;
        }
        .protocol-ide-summary-deck-slot__name {
          color: #475569;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }
        .protocol-ide-summary-empty {
          color: #94a3b8;
          font-style: italic;
          font-size: 0.78rem;
        }
      `}</style>
    </SummaryPanel>
  )
}

// ---------------------------------------------------------------------------
// Tools & Instruments summary
// ---------------------------------------------------------------------------

function ToolsInstrumentsSummaryView({
  summary,
}: {
  summary: ToolsInstrumentsSummary
}): JSX.Element {
  return (
    <SummaryPanel title="Tools & Instruments" icon="🔧" dataTestId="summary-tools-instruments">
      {summary.tools.length > 0 ? (
        <ul className="protocol-ide-summary-tools-list">
          {summary.tools.map((tool, i) => (
            <li key={i} className="protocol-ide-summary-tool-item" data-testid={`tool-item-${i}`}>
              <span className="protocol-ide-summary-tool-item__label">{tool.label}</span>
              {tool.channelCount && (
                <span className="protocol-ide-summary-tool-item__meta">
                  {tool.channelCount}ch
                </span>
              )}
            </li>
          ))}
        </ul>
      ) : (
        <p className="protocol-ide-summary-empty">No tools configured.</p>
      )}
      <style>{`
        .protocol-ide-summary-tools-list {
          list-style: none;
          padding: 0;
          margin: 0;
        }
        .protocol-ide-summary-tool-item {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0.25rem 0;
          border-bottom: 1px solid #f1f3f5;
          font-size: 0.78rem;
        }
        .protocol-ide-summary-tool-item__label {
          font-weight: 500;
          color: #334155;
        }
        .protocol-ide-summary-tool-item__meta {
          font-size: 0.7rem;
          color: #64748b;
          background: #f1f5f9;
          padding: 0.1rem 0.35rem;
          border-radius: 999px;
        }
      `}</style>
    </SummaryPanel>
  )
}

// ---------------------------------------------------------------------------
// Reagents & Concentrations summary
// ---------------------------------------------------------------------------

function ReagentsConcentrationsSummaryView({
  summary,
}: {
  summary: ReagentsConcentrationsSummary
}): JSX.Element {
  return (
    <SummaryPanel title="Reagents & Concentrations" icon="🧫" dataTestId="summary-reagents-concentrations">
      {summary.reagents.length > 0 ? (
        <ul className="protocol-ide-summary-reagents-list">
          {summary.reagents.map((r, i) => (
            <li key={i} className="protocol-ide-summary-reagent-item" data-testid={`reagent-item-${i}`}>
              <span className="protocol-ide-summary-reagent-item__label">{r.label}</span>
              <span className="protocol-ide-summary-reagent-item__meta">
                {r.volume && `${r.volume}${r.unit ?? 'uL'}`}
                {r.concentration && ` @ ${r.concentration}${r.unit ?? 'uM'}`}
              </span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="protocol-ide-summary-empty">No reagents configured.</p>
      )}
      <style>{`
        .protocol-ide-summary-reagents-list {
          list-style: none;
          padding: 0;
          margin: 0;
        }
        .protocol-ide-summary-reagent-item {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0.25rem 0;
          border-bottom: 1px solid #f1f3f5;
          font-size: 0.78rem;
        }
        .protocol-ide-summary-reagent-item__label {
          font-weight: 500;
          color: #334155;
        }
        .protocol-ide-summary-reagent-item__meta {
          font-size: 0.7rem;
          color: #64748b;
        }
      `}</style>
    </SummaryPanel>
  )
}

// ---------------------------------------------------------------------------
// Budget & Cost summary
// ---------------------------------------------------------------------------

function BudgetCostSummaryView({
  summary,
}: {
  summary: BudgetCostSummary
}): JSX.Element {
  return (
    <SummaryPanel title="Budget & Cost" icon="💰" dataTestId="summary-budget-cost">
      <div className="protocol-ide-summary-budget-grid">
        <div className="protocol-ide-summary-budget-row">
          <span className="protocol-ide-summary-budget-label">Lines:</span>
          <span className="protocol-ide-summary-budget-value">{summary.lineCount}</span>
        </div>
        <div className="protocol-ide-summary-budget-row">
          <span className="protocol-ide-summary-budget-label">Approved:</span>
          <span className="protocol-ide-summary-budget-value">{summary.approvedLineCount}</span>
        </div>
        <div className="protocol-ide-summary-budget-row protocol-ide-summary-budget-row--total">
          <span className="protocol-ide-summary-budget-label">Total:</span>
          <span className="protocol-ide-summary-budget-value protocol-ide-summary-budget-value--total">
            ${summary.grandTotal.toFixed(2)}
          </span>
        </div>
      </div>
      <style>{`
        .protocol-ide-summary-budget-grid {
          display: flex;
          flex-direction: column;
          gap: 0.35rem;
        }
        .protocol-ide-summary-budget-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-size: 0.8rem;
        }
        .protocol-ide-summary-budget-label {
          color: #64748b;
          font-weight: 500;
        }
        .protocol-ide-summary-budget-value {
          font-weight: 700;
          color: #0f172a;
        }
        .protocol-ide-summary-budget-row--total {
          border-top: 1px solid #e2e8f0;
          padding-top: 0.4rem;
          margin-top: 0.2rem;
        }
        .protocol-ide-summary-budget-value--total {
          font-size: 0.9rem;
          color: #059669;
        }
      `}</style>
    </SummaryPanel>
  )
}

// ---------------------------------------------------------------------------
// Event graph canvas (review-only — reuses existing graph primitives)
// ---------------------------------------------------------------------------

function EventGraphCanvas({
  eventGraphData,
  issueCards,
  onIssueCardClick,
  onEvidenceClick,
  highlightedEvidenceRefId,
}: {
  eventGraphData?: EventGraphData | null
  issueCards?: IssueCardRef[]
  onIssueCardClick?: (card: IssueCardRef) => void
  onEvidenceClick?: (evidenceRefId: string) => void
  highlightedEvidenceRefId?: string | null
}): JSX.Element {
  const events = eventGraphData?.events ?? []
  const labwares = eventGraphData?.labwares ?? []

  return (
    <div
      className="protocol-ide-event-graph-canvas"
      data-testid="event-graph-canvas"
      role="region"
      aria-label="Event graph review canvas"
    >
      {/* Issue card overlays */}
      {issueCards && issueCards.length > 0 && (
        <div className="protocol-ide-issue-overlays" data-testid="issue-overlays">
          {issueCards.map((card) => (
            <IssueCardOverlay
              key={card.id}
              card={card}
              onEvidenceClick={onEvidenceClick}
            />
          ))}
        </div>
      )}

      {/* Event graph content — review-only */}
      <div className="protocol-ide-event-graph-content" data-testid="event-graph-content">
        {events.length > 0 ? (
          <>
            <div className="protocol-ide-event-graph-header">
              <span className="protocol-ide-event-graph-count">
                {events.length} event{events.length !== 1 ? 's' : ''}
              </span>
              <span className="protocol-ide-event-graph-labware-count">
                {labwares.length} labware
              </span>
            </div>
            <div className="protocol-ide-event-list" data-testid="event-list">
              {events.map((event, i) => {
                const cardForEvent = issueCards?.find(
                  (c) => c.graphRegionId === event.eventId
                )
                const isHighlighted =
                  highlightedEvidenceRefId !== null &&
                  cardForEvent?.evidenceRefId === highlightedEvidenceRefId
                return (
                  <div
                    key={event.eventId || `event-${i}`}
                    className={`protocol-ide-event-item${isHighlighted ? ' protocol-ide-graph-node-highlighted' : ''}`}
                    data-testid={`event-item-${i}`}
                  >
                    <span className="protocol-ide-event-item__type">{event.event_type}</span>
                    <span className="protocol-ide-event-item__summary">
                      {event.event_type === 'transfer'
                        ? `transfer → ${JSON.stringify(event.details?.wells ?? [])}`
                        : JSON.stringify(event.details ?? {})}
                    </span>
                  </div>
                )
              })}
            </div>
          </>
        ) : (
          <div className="protocol-ide-event-graph-empty" data-testid="event-graph-empty">
            <p>No events in the latest compiler output.</p>
            <p className="protocol-ide-event-graph-empty__hint">
              Run the compiler pipeline to generate events.
            </p>
          </div>
        )}
      </div>

      {/* Issue card badges on graph regions */}
      {issueCards && issueCards.length > 0 && (
        <div className="protocol-ide-issue-badges" data-testid="issue-badges">
          {issueCards.map((card) => (
            <IssueCardBadge
              key={card.id}
              card={card}
              onClick={onIssueCardClick}
            />
          ))}
        </div>
      )}

      <style>{`
        .protocol-ide-event-graph-canvas {
          flex: 1;
          position: relative;
          min-height: 0;
          display: flex;
          flex-direction: column;
          overflow: auto;
          background: #fff;
          border: 1px solid #d0d7de;
          border-radius: 8px;
        }
        .protocol-ide-issue-overlays {
          position: absolute;
          top: 0;
          right: 0;
          z-index: 10;
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
          padding: 0.5rem;
        }
        .protocol-ide-event-graph-content {
          flex: 1;
          padding: 0.75rem;
          overflow: auto;
        }
        .protocol-ide-event-graph-header {
          display: flex;
          align-items: center;
          gap: 1rem;
          padding: 0.4rem 0;
          margin-bottom: 0.5rem;
          border-bottom: 1px solid #e9ecef;
        }
        .protocol-ide-event-graph-count,
        .protocol-ide-event-graph-labware-count {
          font-size: 0.78rem;
          color: #64748b;
          font-weight: 500;
        }
        .protocol-ide-event-list {
          display: flex;
          flex-direction: column;
          gap: 0.3rem;
        }
        .protocol-ide-event-item {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.35rem 0.5rem;
          background: #f8f9fa;
          border-radius: 6px;
          font-size: 0.78rem;
          border: 1px solid #e9ecef;
        }
        .protocol-ide-event-item__type {
          font-weight: 700;
          color: #2563eb;
          min-width: 80px;
        }
        .protocol-ide-event-item__summary {
          color: #495057;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }
        .protocol-ide-event-graph-empty {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 3rem 1rem;
          color: #94a3b8;
          text-align: center;
        }
        .protocol-ide-event-graph-empty__hint {
          font-size: 0.78rem;
          margin-top: 0.5rem;
        }
        .protocol-ide-issue-badges {
          position: absolute;
          bottom: 0.75rem;
          left: 0.75rem;
          display: flex;
          flex-wrap: wrap;
          gap: 0.35rem;
          z-index: 5;
        }
      `}</style>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Main review surface
// ---------------------------------------------------------------------------

export function ProtocolIdeGraphReviewSurface({
  session,
  eventGraphData,
  deckLabwareSummary,
  toolsInstrumentsSummary,
  reagentsConcentrationsSummary,
  budgetCostSummary,
  issueCards = [],
  comments = [],
  onIssueCardClick,
  onEvidenceClick,
  highlightedEvidenceRefId,
}: ProtocolIdeGraphReviewSurfaceProps): JSX.Element {
  const hasIssueCards = issueCards.length > 0
  const hasComments = comments.length > 0

  return (
    <div
      className="protocol-ide-graph-review-surface"
      data-testid="protocol-ide-graph-review-surface"
      role="main"
      aria-label="Protocol IDE event-graph review surface"
    >
      {/* Header */}
      <header className="protocol-ide-review-header" data-testid="review-header">
        <div className="protocol-ide-review-header__left">
          <h1 className="protocol-ide-review-title">
            Event-Graph Review — {session.recordId}
          </h1>
          <span
            className="protocol-ide-review-status"
            data-testid="review-status-badge"
          >
            {session.status}
          </span>
        </div>
        <div className="protocol-ide-review-header__right">
          {hasIssueCards && (
            <span
              className="protocol-ide-review-issue-count"
              data-testid="review-issue-count"
            >
              {issueCards.length} issue{issueCards.length !== 1 ? 's' : ''}
            </span>
          )}
          {hasComments && (
            <span
              className="protocol-ide-review-comments"
              data-testid="review-comments"
            >
              {comments.length} comment{comments.length !== 1 ? 's' : ''}
              {' '}
              {comments.map((c) => (
                <CommentBadge key={c.id} comment={c} />
              ))}
            </span>
          )}
        </div>
      </header>

      {/* Main layout: graph canvas (center) + summary panels (right) */}
      <div className="protocol-ide-review-body" data-testid="review-body">
        {/* Center: event graph canvas */}
        <div className="protocol-ide-review-graph" data-testid="review-graph">
          <EventGraphCanvas
            eventGraphData={eventGraphData}
            issueCards={issueCards}
            onIssueCardClick={onIssueCardClick}
            onEvidenceClick={onEvidenceClick}
            highlightedEvidenceRefId={highlightedEvidenceRefId}
          />
        </div>

        {/* Right: summary panels */}
        <aside
          className="protocol-ide-review-summaries"
          data-testid="review-summaries"
          role="complementary"
          aria-label="Summary views"
        >
          {deckLabwareSummary && (
            <DeckLabwareSummaryView summary={deckLabwareSummary} />
          )}
          {toolsInstrumentsSummary && (
            <ToolsInstrumentsSummaryView summary={toolsInstrumentsSummary} />
          )}
          {reagentsConcentrationsSummary && (
            <ReagentsConcentrationsSummaryView summary={reagentsConcentrationsSummary} />
          )}
          {budgetCostSummary && (
            <BudgetCostSummaryView summary={budgetCostSummary} />
          )}
        </aside>
      </div>

      {/* Global styles */}
      <style>{`
        .protocol-ide-graph-review-surface {
          height: 100%;
          display: flex;
          flex-direction: column;
          overflow: hidden;
          background: #f8f9fa;
        }
        .protocol-ide-review-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0.6rem 1rem;
          background: #fff;
          border-bottom: 1px solid #e9ecef;
          flex-shrink: 0;
        }
        .protocol-ide-review-header__left {
          display: flex;
          align-items: center;
          gap: 0.75rem;
        }
        .protocol-ide-review-title {
          font-size: 1rem;
          font-weight: 600;
          color: #212529;
          margin: 0;
        }
        .protocol-ide-review-status {
          font-size: 0.72rem;
          padding: 0.15rem 0.5rem;
          border-radius: 3px;
          font-weight: 500;
          text-transform: capitalize;
          background: #e7f5ff;
          color: #1971c2;
        }
        .protocol-ide-review-issue-count {
          font-size: 0.75rem;
          color: #dc2626;
          font-weight: 600;
        }
        .protocol-ide-review-body {
          flex: 1;
          display: flex;
          min-height: 0;
          overflow: hidden;
          gap: 0.75rem;
          padding: 0.75rem;
        }
        .protocol-ide-review-graph {
          flex: 1;
          min-width: 0;
          display: flex;
          flex-direction: column;
          overflow: hidden;
        }
        .protocol-ide-review-summaries {
          width: 280px;
          min-width: 240px;
          display: flex;
          flex-direction: column;
          gap: 0.6rem;
          overflow-y: auto;
          flex-shrink: 0;
        }
      `}</style>
    </div>
  )
}
