/**
 * ExtractionReviewPage — the biologist-facing review of an extraction draft.
 *
 * Leads with a CONCISE, human-readable "candidate protocol" (≤20 short steps)
 * generated by the LLM from the source document, with a thinking timeline while
 * it works. The machine/role structure (Source, candidates table, role ids) is
 * intentionally NOT shown — the audience is a bench scientist, not a computer
 * scientist. Promote/Reject act on the draft's primary candidate.
 */

import { useParams, useSearchParams } from 'react-router-dom';
import { useEffect, useState, type JSX, type ReactNode } from 'react';
import { promoteThread } from '../shared/api/aiThreadClient';
import { AppShell } from '../shared/shell';
import { WorkspaceTabStrip } from '../shared/shell/WorkspaceTabStrip';
import './extraction.css';

interface Candidate {
  target_kind: string;
  confidence?: number;
  uncertainty?: string;
  evidence_span?: string;
  draft: Record<string, unknown>;
  status?: 'promoted' | 'rejected';
}

interface ExtractionDraft {
  recordId: string;
  kind: 'extraction-draft';
  source_artifact: { kind: string; id: string; locator?: string };
  candidates: Candidate[];
  status: string;
  extractor_profile?: string;
}

function generateConversationRecordId(): string {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const rand = Math.random().toString(36).slice(2, 8);
  return `CONV-${stamp}-${rand}`;
}

/** Wrap the page body in the app shell (GlobalNavbar + tab strip + content). */
function renderShell(body: ReactNode): JSX.Element {
  return (
    <AppShell
      brand="Candidate Protocol"
      layout="workspace"
      topbarTabs={<WorkspaceTabStrip />}
      leftPane={<div className="extraction-scroll">{body}</div>}
    />
  );
}

/** Phases of the extraction "thinking timeline", shown while the LLM works. */
const THINKING_PHASES = [
  'Reading the source document…',
  'Identifying the steps…',
  'Pulling out volumes, times and temperatures…',
  'Condensing to a concise protocol…',
];

export function ExtractionReviewPage(): JSX.Element {
  const params = useParams<{ recordId: string }>();
  const [searchParams] = useSearchParams();
  const recordId = params.recordId ?? searchParams.get('recordId') ?? undefined;

  const [record, setRecord] = useState<ExtractionDraft | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [actionInProgress, setActionInProgress] = useState(false);

  // Concise LLM candidate steps (the primary, biologist-readable artifact).
  const [candidateSteps, setCandidateSteps] = useState<Array<{ ordinal: number; text: string }>>([]);
  const [candidateTitle, setCandidateTitle] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  // Index of the active phase in the thinking timeline (0..N-1).
  const [phase, setPhase] = useState(0);

  // Load the draft record.
  useEffect(() => {
    let cancelled = false;
    if (!recordId) {
      setError('No record ID provided');
      setLoading(false);
      return;
    }
    fetch(`/api/records/${recordId}`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((data) => {
        if (cancelled) return;
        const nested = (data as { record?: { payload?: unknown } }).record;
        const unwrapped =
          (nested && typeof nested === 'object' && 'payload' in (nested as Record<string, unknown>)
            ? (nested as { payload: unknown }).payload
            : nested) ?? data;
        setRecord(unwrapped as ExtractionDraft);
        setLoading(false);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(err.message);
        setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [recordId]);

  // Generate the concise LLM candidate protocol for the source artifact. Keyed
  // on the source artifact id so promoting/rejecting (which update the record
  // object) don't re-trigger generation.
  const srcId = record?.source_artifact?.id;
  useEffect(() => {
    if (!srcId) return;
    let cancelled = false;
    setGenerating(true);
    setGenerateError(null);
    fetch(`/api/extraction/human-steps/${encodeURIComponent(srcId)}`, { method: 'POST' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((d) => {
        if (cancelled) return;
        setCandidateSteps(Array.isArray(d?.steps) ? d.steps : []);
        setCandidateTitle(typeof d?.title === 'string' ? d.title : null);
        setGenerating(false);
      })
      .catch((err) => {
        if (cancelled) return;
        setGenerateError(err instanceof Error ? err.message : String(err));
        setGenerating(false);
      });
    return () => {
      cancelled = true;
    };
  }, [srcId]);

  // Advance the thinking-timeline phase while generating; reset when done.
  useEffect(() => {
    if (!generating) {
      setPhase(0);
      return;
    }
    const t = setInterval(() => setPhase((p) => (p + 1) % THINKING_PHASES.length), 1600);
    return () => clearInterval(t);
  }, [generating]);

  const primaryCandidate = record && record.candidates.length > 0 ? record.candidates[0] : null;
  const isResolved =
    primaryCandidate?.status === 'promoted' || primaryCandidate?.status === 'rejected';

  const setPrimaryStatus = (status: 'promoted' | 'rejected') => {
    setRecord((prev) => {
      if (!prev || prev.candidates.length === 0) return prev;
      const nextCandidates = [...prev.candidates];
      nextCandidates[0] = { ...nextCandidates[0], status };
      return { ...prev, candidates: nextCandidates };
    });
  };

  const promote = async () => {
    if (!recordId || !primaryCandidate || actionInProgress) return;
    setActionInProgress(true);
    try {
      const response = await fetch(`/api/extraction/drafts/${recordId}/candidates/0/promote`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (response.ok) {
        const result = (await response.json()) as { recordId?: string; promotionId?: string };
        setPrimaryStatus('promoted');
        // Auto-promote the originating AI thread (non-fatal on failure).
        const promotedRecordId = result.recordId;
        if (promotedRecordId) {
          const linked: Array<{ recordId: string; kind?: string }> = [
            { recordId: promotedRecordId, kind: 'extracted' },
          ];
          if (result.promotionId) linked.push({ recordId: result.promotionId, kind: 'extraction-promotion' });
          void promoteThread('literature', {
            title: `Extraction promotion · ${promotedRecordId}`,
            recordId: generateConversationRecordId(),
            mode: 'automatic',
            reason: 'extraction-promotion',
            linkedArtifacts: linked,
          }).catch(() => {});
        }
      } else {
        const errBody = await response.json().catch(() => ({}));
        alert(`Promote failed: ${(errBody as { message?: string }).message || response.statusText}`);
      }
    } catch (err) {
      alert(`Promote failed: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setActionInProgress(false);
    }
  };

  const reject = async () => {
    if (!recordId || !primaryCandidate || actionInProgress) return;
    setActionInProgress(true);
    try {
      const response = await fetch(`/api/extraction/drafts/${recordId}/candidates/0/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (response.ok) {
        setPrimaryStatus('rejected');
      } else {
        const errBody = await response.json().catch(() => ({}));
        alert(`Reject failed: ${(errBody as { message?: string }).message || response.statusText}`);
      }
    } catch (err) {
      alert(`Reject failed: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setActionInProgress(false);
    }
  };

  if (loading) {
    return renderShell(<div className="extraction-review"><p>Loading candidate protocol...</p></div>);
  }
  if (error) {
    return renderShell(<div className="extraction-review"><p role="alert">Failed to load: {error}</p></div>);
  }
  if (!record) {
    return renderShell(<div className="extraction-review"><p>Not found</p></div>);
  }

  return renderShell(
    <div className="extraction-review">
      <h1>Candidate Protocol</h1>
      <p className="extraction-review__sub">{record.recordId}</p>

      <section className="candidate-protocol" data-testid="candidate-protocol">
        <div className="candidate-protocol__head">
          <h2>{candidateTitle ?? 'Candidate protocol'}</h2>
          {generateError && <span className="candidate-protocol__err">couldn't regenerate</span>}
        </div>

        {generating ? (
          <div className="thinking" data-testid="thinking" role="status" aria-live="polite">
            <div className="thinking__spinner" aria-hidden />
            <p className="thinking__phase">{THINKING_PHASES[phase]}</p>
            <ul className="thinking__track" aria-hidden>
              {THINKING_PHASES.map((p, i) => (
                <li
                  key={p}
                  className={
                    i < phase ? 'thinking__track-item thinking__track-item--done' : 'thinking__track-item'
                  }
                >
                  {i + 1}
                </li>
              ))}
            </ul>
          </div>
        ) : generateError ? (
          <p role="alert">Couldn't generate the candidate protocol: {generateError}</p>
        ) : candidateSteps.length === 0 ? (
          <p>No candidate protocol was generated for this source.</p>
        ) : (
          <ol className="candidate-protocol__list">
            {candidateSteps.map((s) => (
              <li key={s.ordinal} className="candidate-protocol__step">
                <span className="candidate-protocol__num" aria-hidden>
                  {s.ordinal}.
                </span>
                <span className="candidate-protocol__text">{s.text}</span>
              </li>
            ))}
          </ol>
        )}

        {primaryCandidate ? (
          <div className="candidate-protocol__actions">
            <button
              type="button"
              className="candidate-protocol__btn candidate-protocol__btn--promote"
              onClick={() => void promote()}
              disabled={isResolved || actionInProgress || generating}
            >
              Promote
            </button>
            <button
              type="button"
              className="candidate-protocol__btn candidate-protocol__btn--reject"
              onClick={() => void reject()}
              disabled={isResolved || actionInProgress || generating}
            >
              Reject
            </button>
            {isResolved ? <span className="candidate-protocol__status">{primaryCandidate.status}</span> : null}
          </div>
        ) : null}
      </section>
    </div>,
  );
}
