/**
 * ProtocolBuilderContext — state management for the standalone protocol builder.
 *
 * Holds the extracted candidate, step toggles, inline overrides, labware mappings,
 * draft events, promotion state, and the active right-panel tab. Survives tab-switching
 * and page navigation within the /protocol-builder route.
 */

import { createContext, useContext, useState, useCallback, useMemo, type ReactNode } from 'react'
import type { AiProtocolCandidateSummary } from '../types/ai'
import type { PlateEvent } from '../types/events'

export interface StepOverride {
  stepKey: string
  volume?: string | null
  temperature?: string | null
  duration?: string | null
  concentration?: string | null
}

export interface LabwareMapping {
  /** Role label from the candidate (e.g. "96-well block"). */
  roleLabel: string
  /** Concrete labware record selected from the library. */
  labwareRecordId: string
  /** Deck slot assignment (e.g. "A1", "A2", ...). */
  deckSlot: string
}

export interface DraftLabware {
  labwareId: string
  labwareType: string
  name: string
  deckSlot?: string
  reason?: string
}

interface ProtocolBuilderState {
  candidate: AiProtocolCandidateSummary | null
  sourceText: string | null
  skippedSteps: Set<string>
  overrides: StepOverride[]
  mappings: LabwareMapping[]
  activeTab: 'preview' | 'configure' | 'draft' | 'promote'
  /** Ghost events generated by the AI draft. */
  draftEvents: PlateEvent[] | null
  /** Labware placements from the draft. */
  draftLabwares: DraftLabware[] | null
  /** Iteration counter for redrafts (0 = initial draft). */
  draftIteration: number
  /** Whether the promote request is in-flight. */
  isPromoting: boolean
  /** Whether the draft generation request is in-flight. */
  isDrafting: boolean
  /** Number of events committed after successful promotion. */
  promotedEventCount: number | null
  /** Record ID assigned after promotion. */
  promotedRecordId: string | null
  /** Whether promotion was successful. */
  promoted: boolean
  /** Whether an export request is in-flight. */
  exporting: boolean
}

interface ProtocolBuilderActions {
  setCandidate: (c: AiProtocolCandidateSummary | null) => void
  setSourceText: (t: string | null) => void
  toggleStep: (stepKey: string, enabled: boolean) => void
  setOverride: (stepKey: string, field: keyof StepOverride, value: string | null) => void
  setMapping: (mapping: LabwareMapping) => void
  setActiveTab: (tab: 'preview' | 'configure' | 'draft' | 'promote') => void
  resetConfig: () => void
  /** Set the draft events and labware placements. */
  setDraft: (events: PlateEvent[], labwares: DraftLabware[], iteration: number) => void
  /** Clear the draft state. */
  clearDraft: () => void
  /** Mark promotion as successful with event count and record ID. */
  setPromoted: (count: number, recordId: string) => void
  /** Set the promoting flag. */
  setPromoting: (v: boolean) => void
  /** Set the drafting flag. */
  setDrafting: (v: boolean) => void
  /** Set the exporting flag. */
  setExporting: (v: boolean) => void
  /** Reset everything including promoted state — start fresh. */
  resetAll: () => void
}

const ProtocolBuilderContext = createContext<{
  state: ProtocolBuilderState
  actions: ProtocolBuilderActions
} | null>(null)

export function useProtocolBuilderState() {
  const ctx = useContext(ProtocolBuilderContext)
  if (!ctx) {
    throw new Error('useProtocolBuilderState must be used inside ProtocolBuilderProvider')
  }
  return ctx
}

export function ProtocolBuilderProvider({ children }: { children: ReactNode }) {
  const [candidate, setCandidateState] = useState<AiProtocolCandidateSummary | null>(null)
  const [sourceText, setSourceTextState] = useState<string | null>(null)
  const [skippedSteps, setSkippedStepsState] = useState<Set<string>>(new Set())
  const [overrides, setOverridesState] = useState<StepOverride[]>([])
  const [mappings, setMappingsState] = useState<LabwareMapping[]>([])
  const [activeTab, setActiveTabState] = useState<'preview' | 'configure' | 'draft' | 'promote'>('preview')
  const [draftEvents, setDraftEventsState] = useState<PlateEvent[] | null>(null)
  const [draftLabwares, setDraftLabwaresState] = useState<DraftLabware[] | null>(null)
  const [draftIteration, setDraftIterationState] = useState<number>(0)
  const [isPromoting, setIsPromotingState] = useState(false)
  const [isDrafting, setIsDraftingState] = useState(false)
  const [promotedEventCount, setPromotedEventCountState] = useState<number | null>(null)
  const [promotedRecordId, setPromotedRecordIdState] = useState<string | null>(null)
  const [promoted, setPromotedState] = useState(false)
  const [exporting, setExportingState] = useState(false)

  const toggleStep = useCallback((stepKey: string, enabled: boolean) => {
    setSkippedStepsState((prev) => {
      const next = new Set(prev)
      if (enabled) next.delete(stepKey)
      else next.add(stepKey)
      return next
    })
  }, [])

  const setOverride = useCallback(
    (stepKey: string, field: keyof StepOverride, value: string | null) => {
      setOverridesState((prev) => {
        const existing = prev.find((o) => o.stepKey === stepKey)
        if (!existing && !value) return prev
        if (existing) {
          return prev.map((o) =>
            o.stepKey === stepKey ? { ...o, [field]: value } : o,
          )
        }
        return [...prev, { stepKey, [field]: value }]
      })
    },
    [],
  )

  const setMapping = useCallback((mapping: LabwareMapping) => {
    setMappingsState((prev) => {
      const idx = prev.findIndex((m) => m.roleLabel === mapping.roleLabel)
      if (idx >= 0) {
        const next = [...prev]
        next[idx] = mapping
        return next
      }
      return [...prev, mapping]
    })
  }, [])

  const setDraft = useCallback((events: PlateEvent[], labwares: DraftLabware[], iteration: number) => {
    setDraftEventsState(events)
    setDraftLabwaresState(labwares)
    setDraftIterationState(iteration)
    setActiveTabState('draft')
  }, [])

  const clearDraft = useCallback(() => {
    setDraftEventsState(null)
    setDraftLabwaresState(null)
    setDraftIterationState(0)
  }, [])

  const setPromoted = useCallback((count: number, recordId: string) => {
    setPromotedEventCountState(count)
    setPromotedRecordIdState(recordId)
    setPromotedState(true)
  }, [])

  const resetConfig = useCallback(() => {
    setCandidateState(null)
    setSourceTextState(null)
    setSkippedStepsState(new Set())
    setOverridesState([])
    setMappingsState([])
    setActiveTabState('preview')
    setIsDraftingState(false)
  }, [])

  const resetAll = useCallback(() => {
    setCandidateState(null)
    setSourceTextState(null)
    setSkippedStepsState(new Set())
    setOverridesState([])
    setMappingsState([])
    setActiveTabState('preview')
    setDraftEventsState(null)
    setDraftLabwaresState(null)
    setDraftIterationState(0)
    setIsPromotingState(false)
    setIsDraftingState(false)
    setPromotedEventCountState(null)
    setPromotedRecordIdState(null)
    setPromotedState(false)
    setExportingState(false)
  }, [])

  const state: ProtocolBuilderState = useMemo(
    () => ({
      candidate,
      sourceText,
      skippedSteps,
      overrides,
      mappings,
      activeTab,
      draftEvents,
      draftLabwares,
      draftIteration,
      isPromoting,
      isDrafting,
      promotedEventCount,
      promotedRecordId,
      promoted,
      exporting,
    }),
    [candidate, sourceText, skippedSteps, overrides, mappings, activeTab,
     draftEvents, draftLabwares, draftIteration, isPromoting, isDrafting,
     promotedEventCount, promotedRecordId, promoted, exporting],
  )

  const actions: ProtocolBuilderActions = useMemo(
    () => ({
      setCandidate: setCandidateState,
      setSourceText: setSourceTextState,
      toggleStep,
      setOverride,
      setMapping,
      setActiveTab: setActiveTabState,
      resetConfig,
      setDraft,
      clearDraft,
      setPromoted,
      setPromoting: setIsPromotingState,
      setDrafting: setIsDraftingState,
      setExporting: setExportingState,
      resetAll,
    }),
    [toggleStep, setOverride, setMapping, resetConfig, setDraft, clearDraft, setPromoted, resetAll],
  )

  return (
    <ProtocolBuilderContext.Provider value={{ state, actions }}>
      {children}
    </ProtocolBuilderContext.Provider>
  )
}
